// manish/angular212prjs/prj2/src/app/components/profile.component.ts
import { Component } from '@angular/core';
import {GithubService} from '../services/github.service';

@Component({
  moduleId: module.id,
  selector: 'profile',
  templateUrl: 'profile.component.html',
})
export class ProfileComponent  { 
  
  user: any;
  repos: any[];
  username: string;

  constructor(private _githubService: GithubService) {
    this.user = false;
  }

  searchUser() {
    this._githubService.updateUser(this.username);
    
    this._githubService.getUser().subscribe(user => {
      console.log('user is ', user);
      this.user = user;
    });
    
    this._githubService.getRepos().subscribe(repos => {
      console.log('repos is ', repos);
      this.repos = repos;
    });
  }

}

<div class="row">
  <div class="col-md-12">
    <form class="well">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Enter Github Username..." [(ngModel)]="username" name="username" (keyup)="searchUser()" />
      </div>
    </form>
  </div>
</div>
 

 <div *ngIf="user">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">{{user.name}}</h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-4">
          <img class="img-responsive img-rounded img-thumbnail" src="{{user.avatar_url}}" />
          <a href="{{user.html_url}}" target="_blank" class="btn btn-default btn-block">View Profile</a>
        </div>
        <div class="col-md-8">
          <div class="stats">
            <span class="label label-default">{{user.public_repos}} Public Repos</span>
            <span class="label label-primary">{{user.public_gists}} Public Gists</span>
            <span class="label label-success">{{user.followers}} Followers</span>
            <span class="label label-info">{{user.following}} Following</span>
          </div>
          <br />
          <ul class="list-group">
            <li class="list-group-item"><strong>Username: </strong> {{user.login}}</li>
            <li class="list-group-item"><strong>Location: </strong> {{user.location}}</li>
            <li class="list-group-item"><strong>Email: </strong> {{user.email}}</li>
            <li class="list-group-item"><strong>Blog: </strong> {{user.blog}}</li>
            <li class="list-group-item"><strong>Member Since: </strong> {{user.created_at}}</li>
          </ul>
          
        </div>
      </div>
    </div>
  </div>
  
  
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">User Repos</h3>
        </div>
        <div class="panel-body">
            <div *ngFor="let repo of repos">
               <div class="row">
                 <div class="col-md-9">
                    <h4><a href="{{repo.html_url}}" target="_blank">{{repo.name}}</a></h4>
                    <p>{{repo.description}}</p>
                 </div>
                 <div class="col-md-3">
                  <span class="label label-default">{{repo.watchers}} Watchers</span>
                  <span class="label label-primary">{{repo.forks}} Forks</span>
                 </div>
               </div>
               
               <hr />
               
               
               
            </div>
        </div>
    </div>
</div>

// class/react/react/flux2/srcbackup2/components/Profile.js
import React, { Component } from 'react';

import RepoList from './RepoList.js';

class Profile extends Component {
  render() {
    return (
      <div>
      
        <div className="panel panel-default">
          <div className="panel-heading">
            <h3 className="panel-title">{this.props.userData.name}</h3>
          </div>
          <div className="panel-body">
      
            <div className="row">
              <div className="col-md-4">
                <img src={this.props.userData.avatar_url} alt="" className="thumbnail" style={{width: "100%"}} />
              </div>
              <div className="col-md-8">
                <div className="row">
                  <div className="col-md-12">
                    <span className="label label-default">{this.props.userData.public_repos} Repos</span>
                    <span className="label label-primary">{this.props.userData.public_gists} Public Gists</span>
                    <span className="label label-success">{this.props.userData.followers} Followers</span>
                    <span className="label label-info">{this.props.userData.following} Following</span>
                  </div>
                </div>
                
                <hr />
                
                <div className="row">
                  <div className="col-md-12">
                    <ul className="list-group">
                      <li className="list-group-item"><strong>Username: </strong> {this.props.userData.login}</li>
                      <li className="list-group-item"><strong>Location: </strong> {this.props.userData.location}</li>
                      <li className="list-group-item"><strong>Email Address: </strong> {this.props.userData.email}</li>
                    </ul>
                  </div>
                </div>
      
                <br />
                <a href={this.props.userData.html_url} target="_blank" className="btn btn-primary">View Profile</a>
      
      
      
              </div>
            </div>
      
          </div>
      
      
      
      
        </div>
      
      
      
          
          <hr />
          <h3>User Repositories</h3>
          <RepoList userRepos={this.props.userRepos} />
          
      
      </div>
    );
  }
}

export default Profile;
